# Pull base SDK image
FROM espressif/idf:release-v4.3

# set work directory
WORKDIR /usr/src/app

#Copy firmware project
COPY . ./

#Everything should happen interactively from here
#Follow build instructions as advised by Espressif
